import org.springframework.boot.gradle.tasks.bundling.BootJar

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("io.github.mi.kotlin-library-conventions")
}

dependencies {
//    api(project(":list"))
}

tasks {
    named<BootJar>("bootJar") {
        enabled = false
    }
}